version: 2.1
jobs:
  # 'build' is the 1st and only job
  build:
    working_directory: ~/repo
    docker:
      # Pull CircleCI Docker image for Go as the testing environ.
      - image: circleci/golang:1.14.6
    steps:
      # Check out project code from remote repo.
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go get ./...
      # Cache deps after installation.
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run tests
          command: go test -v
